steps:
  - name: ubuntu
    args:
      - /bin/bash
      - '-c'
      - |
        echo "Welcome to DevOps HQ!"
        sleep 20  # Sleep for 20 minutes (20 seconds)
        echo "execution completed!"
timeout: 30s
options:
  logging: CLOUD_LOGGING_ONLY